name: master
on:
  push:
    branches: [master]

jobs:
  build:
    name: Build master branch
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run unit tests
        shell: bash
        run: ./gradlew --continue testRelease
      - name: Build
        run: ./gradlew build
