name: Release build

on: [pull_request]
#on:
#  release:
#    types: [published]

jobs:
  release:
    name: Release build
    runs-on: [ubuntu-latest]
    env:
      GIT_TAG: TEST
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test env variables
        shell: bash
        run: ./gradlew testTask
#      - name: Run unit tests
#        shell: bash
#        run: ./gradlew --continue testRelease
#      - name: Upload to Bintray
#        run: ./gradlew build publish bintrayUpload --stacktrace --no-daemon -PBINTRAY_USER=${{secrets.BINTRAY_USER}} -PBINTRAY_KEY=${{secrets.BINTRAY_KEY}} -PBINTRAY_GPG_KEY=${{secrets.BINTRAY_GPG_KEY}}
